version: '3.9'
services:
  telegram_bot:
    build:
      context: ./bots/telegram
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ai_api
    restart: always

#  whatsapp_bot:
#    build: ./bots/whatsapp
#    env_file:
#      - .env
#    depends_on:
#      - ai_api
#    restart: always

  ai_api:
    build:
      context: .
      dockerfile: services/ai_api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

#  init_db:
#    build:
#      context: .
#      dockerfile: services/init_db/Dockerfile
#    depends_on:
#      - database
#    environment:
#      - DATABASE_URL=postgresql+asyncpg://postgres:example@database:5432/appdb
#    command: [ "python", "init_db.py" ]

#  admin_panel:
#    build: ./admin
#    env_file:
#      - .env
#    ports:
#      - "5000:5000"
#    depends_on:
#      - database
#    restart: always

volumes:
  db_data: