services:
  telegram_bot:
    build:
      context: ./bots/telegram
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ai_api
    restart: unless-stopped

  whatsapp_bot:
    build:
      context: .
      dockerfile: bots/whatsapp/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - ai_api

  ai_api:
    build:
      context: .
      dockerfile: services/ai_api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - init_db
    restart: unless-stopped

  database:
    image: postgres:15.14
    command: >
      postgres
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
      -c max_connections=20
      -c temp_file_limit=512MB
      -c jit=off
      -c log_min_duration_statement=500ms
      -c log_connections=on
      -c log_disconnections=on
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  init_db:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database

#  admin_panel:
#    build: ./admin
#    env_file:
#      - .env
#    ports:
#      - "5000:5000"
#    depends_on:
#      - database
#    restart: always
#  web:
#    build:
#      context: ./web
#      dockerfile: Dockerfile
#    container_name: obi_web
#    ports:
#      - "3000:3000"

volumes:
  db_data: